version: '3.1'

services:
  mongodb:
    image: mongo:7.0.16
    restart: always
    # command: --authenticationDatabase admin
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      # MONGO_INITDB_DATABASE: chat_database
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db  

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
volumes:
  mongodb_data:      