name: CI/CD Pipeling

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    env: 
      IMAGE_NAME: custom-agent-flow
      IMAGE_TAG: v1
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: action/checkout@v4
      - name: Set Up Python
        uses: action/setup-pyhton@v5
        with:
          pyhton-version: '3.12'
      - name: Insatll dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run test    
        run: |
          pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
